package com.toofifty.easyblastfurnace.utils;

import net.runelite.api.gameval.ItemID;

public enum Graceful {
	HEAD(new int[] {
			ItemID.GRACEFUL_HOOD_WORN, ItemID.ZEAH_GRACEFUL_HOOD_ARCEUUS, ItemID.ZEAH_GRACEFUL_HOOD_ARCEUUS_WORN, ItemID.ZEAH_GRACEFUL_HOOD_PISCARILIUS,
			ItemID.ZEAH_GRACEFUL_HOOD_PISCARILIUS_WORN, ItemID.ZEAH_GRACEFUL_HOOD_LOVAKENGJ, ItemID.ZEAH_GRACEFUL_HOOD_LOVAKENGJ_WORN, ItemID.ZEAH_GRACEFUL_HOOD_SHAYZIEN,
			ItemID.ZEAH_GRACEFUL_HOOD_SHAYZIEN_WORN, ItemID.ZEAH_GRACEFUL_HOOD_HOSIDIUS, ItemID.ZEAH_GRACEFUL_HOOD_HOSIDIUS_WORN, ItemID.ZEAH_GRACEFUL_HOOD_KOUREND,
			ItemID.ZEAH_GRACEFUL_HOOD_KOUREND_WORN, ItemID.GRACEFUL_HOOD_SKILLCAPECOLOUR, ItemID.GRACEFUL_HOOD_SKILLCAPECOLOUR_WORN, ItemID.GRACEFUL_HOOD_HALLOWED,
			ItemID.GRACEFUL_HOOD_HALLOWED_WORN, ItemID.GRACEFUL_HOOD_TRAILBLAZER, ItemID.GRACEFUL_HOOD_TRAILBLAZER_WORN, ItemID.GRACEFUL_HOOD_WYRM, ItemID.GRACEFUL_HOOD_WYRM_WORN
	}, 3),

	BODY(new int[] {
			ItemID.GRACEFUL_TOP, ItemID.ZEAH_GRACEFUL_TOP_ARCEUUS, ItemID.ZEAH_GRACEFUL_TOP_ARCEUUS_WORN, ItemID.ZEAH_GRACEFUL_TOP_PISCARILIUS, ItemID.ZEAH_GRACEFUL_TOP_PISCARILIUS_WORN,
			ItemID.ZEAH_GRACEFUL_TOP_LOVAKENGJ, ItemID.ZEAH_GRACEFUL_TOP_LOVAKENGJ_WORN, ItemID.ZEAH_GRACEFUL_TOP_SHAYZIEN, ItemID.ZEAH_GRACEFUL_TOP_SHAYZIEN_WORN, ItemID.ZEAH_GRACEFUL_TOP_HOSIDIUS,
			ItemID.ZEAH_GRACEFUL_TOP_HOSIDIUS_WORN, ItemID.ZEAH_GRACEFUL_TOP_KOUREND, ItemID.ZEAH_GRACEFUL_TOP_KOUREND_WORN, ItemID.GRACEFUL_TOP_SKILLCAPECOLOUR, ItemID.GRACEFUL_TOP_SKILLCAPECOLOUR_WORN,
			ItemID.GRACEFUL_TOP_HALLOWED, ItemID.GRACEFUL_TOP_HALLOWED_WORN, ItemID.GRACEFUL_TOP_TRAILBLAZER, ItemID.GRACEFUL_TOP_TRAILBLAZER_WORN, ItemID.GRACEFUL_TOP_WYRM, ItemID.GRACEFUL_TOP_WYRM_WORN
	}, 4),

	LEGS(new int[] {
			ItemID.GRACEFUL_LEGS, ItemID.ZEAH_GRACEFUL_LEGS_ARCEUUS, ItemID.ZEAH_GRACEFUL_LEGS_ARCEUUS_WORN, ItemID.ZEAH_GRACEFUL_LEGS_PISCARILIUS, ItemID.ZEAH_GRACEFUL_LEGS_PISCARILIUS_WORN,
			ItemID.ZEAH_GRACEFUL_LEGS_LOVAKENGJ, ItemID.ZEAH_GRACEFUL_LEGS_LOVAKENGJ_WORN, ItemID.ZEAH_GRACEFUL_LEGS_SHAYZIEN, ItemID.ZEAH_GRACEFUL_LEGS_SHAYZIEN_WORN, ItemID.ZEAH_GRACEFUL_LEGS_HOSIDIUS,
			ItemID.ZEAH_GRACEFUL_LEGS_HOSIDIUS_WORN, ItemID.ZEAH_GRACEFUL_LEGS_KOUREND, ItemID.ZEAH_GRACEFUL_LEGS_KOUREND_WORN, ItemID.GRACEFUL_LEGS_SKILLCAPECOLOUR, ItemID.GRACEFUL_LEGS_SKILLCAPECOLOUR_WORN,
			ItemID.GRACEFUL_LEGS_HALLOWED, ItemID.GRACEFUL_LEGS_HALLOWED_WORN, ItemID.GRACEFUL_LEGS_TRAILBLAZER, ItemID.GRACEFUL_LEGS_TRAILBLAZER_WORN, ItemID.GRACEFUL_LEGS_WYRM, ItemID.GRACEFUL_LEGS_WYRM_WORN
	}, 4),

	GLOVES(new int[] {
			ItemID.GRACEFUL_GLOVES, ItemID.ZEAH_GRACEFUL_GLOVES_ARCEUUS, ItemID.ZEAH_GRACEFUL_GLOVES_ARCEUUS_WORN, ItemID.ZEAH_GRACEFUL_GLOVES_PISCARILIUS, ItemID.ZEAH_GRACEFUL_GLOVES_PISCARILIUS_WORN,
			ItemID.ZEAH_GRACEFUL_GLOVES_LOVAKENGJ, ItemID.ZEAH_GRACEFUL_GLOVES_LOVAKENGJ_WORN, ItemID.ZEAH_GRACEFUL_GLOVES_SHAYZIEN, ItemID.ZEAH_GRACEFUL_GLOVES_SHAYZIEN_WORN, ItemID.ZEAH_GRACEFUL_GLOVES_HOSIDIUS,
			ItemID.ZEAH_GRACEFUL_GLOVES_HOSIDIUS_WORN, ItemID.ZEAH_GRACEFUL_GLOVES_KOUREND, ItemID.ZEAH_GRACEFUL_GLOVES_KOUREND_WORN, ItemID.GRACEFUL_GLOVES_SKILLCAPECOLOUR, ItemID.GRACEFUL_GLOVES_SKILLCAPECOLOUR_WORN,
			ItemID.GRACEFUL_GLOVES_HALLOWED, ItemID.GRACEFUL_GLOVES_HALLOWED_WORN, ItemID.GRACEFUL_GLOVES_TRAILBLAZER, ItemID.GRACEFUL_GLOVES_TRAILBLAZER_WORN, ItemID.GRACEFUL_GLOVES_WYRM, ItemID.GRACEFUL_GLOVES_WYRM_WORN
	}, 3),

	BOOTS(new int[] {
			ItemID.GRACEFUL_BOOTS, ItemID.ZEAH_GRACEFUL_BOOTS_ARCEUUS, ItemID.ZEAH_GRACEFUL_BOOTS_ARCEUUS_WORN, ItemID.ZEAH_GRACEFUL_BOOTS_PISCARILIUS, ItemID.ZEAH_GRACEFUL_BOOTS_PISCARILIUS_WORN, ItemID.ZEAH_GRACEFUL_BOOTS_LOVAKENGJ,
			ItemID.ZEAH_GRACEFUL_BOOTS_LOVAKENGJ_WORN, ItemID.ZEAH_GRACEFUL_BOOTS_SHAYZIEN, ItemID.ZEAH_GRACEFUL_BOOTS_SHAYZIEN_WORN, ItemID.ZEAH_GRACEFUL_BOOTS_HOSIDIUS, ItemID.ZEAH_GRACEFUL_BOOTS_HOSIDIUS_WORN,
			ItemID.ZEAH_GRACEFUL_BOOTS_KOUREND, ItemID.ZEAH_GRACEFUL_BOOTS_KOUREND_WORN, ItemID.GRACEFUL_BOOTS_SKILLCAPECOLOUR, ItemID.GRACEFUL_BOOTS_SKILLCAPECOLOUR_WORN, ItemID.GRACEFUL_BOOTS_HALLOWED,
			ItemID.GRACEFUL_BOOTS_HALLOWED_WORN, ItemID.GRACEFUL_BOOTS_TRAILBLAZER, ItemID.GRACEFUL_BOOTS_TRAILBLAZER_WORN, ItemID.GRACEFUL_BOOTS_WYRM, ItemID.GRACEFUL_BOOTS_WYRM_WORN
	}, 3),

	CAPE(new int[] {
			ItemID.GRACEFUL_CAPE, ItemID.ZEAH_GRACEFUL_CAPE_ARCEUUS, ItemID.ZEAH_GRACEFUL_CAPE_ARCEUUS_WORN, ItemID.ZEAH_GRACEFUL_CAPE_PISCARILIUS, ItemID.ZEAH_GRACEFUL_CAPE_PISCARILIUS_WORN, ItemID.ZEAH_GRACEFUL_CAPE_LOVAKENGJ,
			ItemID.ZEAH_GRACEFUL_CAPE_LOVAKENGJ_WORN, ItemID.ZEAH_GRACEFUL_CAPE_SHAYZIEN, ItemID.ZEAH_GRACEFUL_CAPE_SHAYZIEN_WORN, ItemID.ZEAH_GRACEFUL_CAPE_HOSIDIUS, ItemID.ZEAH_GRACEFUL_CAPE_HOSIDIUS_WORN,
			ItemID.ZEAH_GRACEFUL_CAPE_KOUREND, ItemID.ZEAH_GRACEFUL_CAPE_KOUREND_WORN, ItemID.GRACEFUL_CAPE_SKILLCAPECOLOUR, ItemID.GRACEFUL_CAPE_SKILLCAPECOLOUR_WORN, ItemID.GRACEFUL_CAPE_HALLOWED,
			ItemID.GRACEFUL_CAPE_HALLOWED_WORN, ItemID.GRACEFUL_CAPE_TRAILBLAZER, ItemID.GRACEFUL_CAPE_TRAILBLAZER_WORN, ItemID.GRACEFUL_CAPE_WYRM, ItemID.GRACEFUL_CAPE_WYRM_WORN,
			ItemID.SKILLCAPE_AGILITY,ItemID.SKILLCAPE_AGILITY_WORN, ItemID.SKILLCAPE_AGILITY_TRIMMED, ItemID.SKILLCAPE_AGILITY_TRIMMED_WORN, ItemID.SKILLCAPE_MAX, ItemID.SKILLCAPE_MAX_WORN
	}, 3);

	public final int[] items;

	public final int boost;

	Graceful(int[] items, int boost)
	{
		this.items = items;
		this.boost = boost;
	}
}
